# Generated by Django 5.2.10 on 2026-01-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("progress", "Progress"),
                            ("skill", "Skill"),
                            ("challenge", "Challenge"),
                            ("special", "Special"),
                        ],
                        default="progress",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(
                        default=dict,
                        help_text="Conditions to unlock this achievement",
                        verbose_name="requirements",
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(default=50, verbose_name="XP reward"),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="achievements/",
                        verbose_name="badge image",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="is hidden"),
                ),
                ("is_rare", models.BooleanField(default=False, verbose_name="is rare")),
            ],
            options={
                "verbose_name": "achievement",
                "verbose_name_plural": "achievements",
            },
        ),
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
            ],
            options={
                "verbose_name": "module progress",
                "verbose_name_plural": "module progress",
            },
        ),
        migrations.CreateModel(
            name="Streak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="current streak"
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="longest streak"
                    ),
                ),
                (
                    "last_activity_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="last activity date"
                    ),
                ),
            ],
            options={
                "verbose_name": "streak",
                "verbose_name_plural": "streaks",
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="unlocked at"),
                ),
            ],
            options={
                "verbose_name": "user achievement",
                "verbose_name_plural": "user achievements",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage",
                    models.PositiveIntegerField(default=0, verbose_name="percentage"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="started at"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="last accessed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
            ],
            options={
                "verbose_name": "user progress",
                "verbose_name_plural": "user progress",
            },
        ),
        migrations.CreateModel(
            name="UserXP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_xp",
                    models.PositiveIntegerField(default=0, verbose_name="total XP"),
                ),
                ("level", models.PositiveIntegerField(default=1, verbose_name="level")),
            ],
            options={
                "verbose_name": "user XP",
                "verbose_name_plural": "user XP",
            },
        ),
        migrations.CreateModel(
            name="XPTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="amount")),
                ("reason", models.CharField(max_length=200, verbose_name="reason")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "XP transaction",
                "verbose_name_plural": "XP transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.BooleanField(default=False, verbose_name="started")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "xp_awarded",
                    models.BooleanField(default=False, verbose_name="XP awarded"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson progress",
                "verbose_name_plural": "lesson progress",
            },
        ),
    ]
