# Generated by Django 5.2.10 on 2026-01-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill_assessment_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='skill assessment completed at'),
        ),
    ]
