# Generated by Django 5.2.10 on 2026-01-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="icon"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CoursePrerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "course prerequisite",
                "verbose_name_plural": "course prerequisites",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(max_length=200, verbose_name="slug")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("video", "Video"),
                            ("interactive", "Interactive"),
                            ("quiz", "Quiz"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="content type",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "video_url",
                    models.URLField(blank=True, default="", verbose_name="video URL"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "requires_lab_completion",
                    models.BooleanField(
                        default=False,
                        help_text="Whether completing the lab is required to finish this lesson",
                        verbose_name="requires lab completion",
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(default=10, verbose_name="XP reward"),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=10, verbose_name="estimated duration (minutes)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LessonResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("link", "External Link"),
                            ("code", "Code Repository"),
                            ("tool", "Tool Reference"),
                        ],
                        max_length=20,
                        verbose_name="resource type",
                    ),
                ),
                ("url", models.URLField(blank=True, default="", verbose_name="URL")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="lessons/resources/",
                        verbose_name="file",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson resource",
                "verbose_name_plural": "lesson resources",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "requires_previous",
                    models.BooleanField(
                        default=True,
                        help_text="Whether completion of previous module is required",
                        verbose_name="requires previous module",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "module",
                "verbose_name_plural": "modules",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=70, verbose_name="passing score percentage"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(default=3, verbose_name="max attempts"),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="time limit (minutes)"
                    ),
                ),
            ],
            options={
                "verbose_name": "quiz",
                "verbose_name_plural": "quizzes",
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.CharField(max_length=500, verbose_name="answer"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="is correct"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
            ],
            options={
                "verbose_name": "quiz answer",
                "verbose_name_plural": "quiz answers",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="question")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Choice"),
                            ("multiple", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("text", "Text Answer"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="question type",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Shown after answering",
                        verbose_name="explanation",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "points",
                    models.PositiveIntegerField(default=1, verbose_name="points"),
                ),
            ],
            options={
                "verbose_name": "quiz question",
                "verbose_name_plural": "quiz questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="short description"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="level",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/thumbnails/",
                        verbose_name="thumbnail",
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(default=100, verbose_name="XP reward"),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=60, verbose_name="estimated duration (minutes)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="is featured"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="courses.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "ordering": ["level", "title"],
            },
        ),
    ]
