# Generated by Django 5.2.10 on 2026-01-17 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='score percentage')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='points earned')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='total points')),
                ('passed', models.BooleanField(default=False, verbose_name='passed')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('time_taken', models.PositiveIntegerField(blank=True, null=True, verbose_name='time taken (seconds)')),
                ('answers', models.JSONField(default=dict, verbose_name='answers')),
                ('xp_awarded', models.BooleanField(default=False, verbose_name='XP awarded')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quiz attempt',
                'verbose_name_plural': 'quiz attempts',
                'ordering': ['-started_at'],
            },
        ),
    ]
