# Generated by Django 5.2.10 on 2026-01-17 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quizattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('quiz', 'Quiz'), ('skill_assessment', 'Skill Assessment')], max_length=20, verbose_name='session type')),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='session token')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('submitted', models.BooleanField(default=False, verbose_name='submitted')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assessment session',
                'verbose_name_plural': 'assessment sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_created', 'Session Created'), ('submission_success', 'Submission Success'), ('submission_failed', 'Submission Failed'), ('validation_error', 'Validation Error'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('attempt_limit_exceeded', 'Attempt Limit Exceeded'), ('suspicious_timing', 'Suspicious Timing'), ('session_hijack_attempt', 'Session Hijack Attempt'), ('rate_limit_hit', 'Rate Limit Hit'), ('minimum_time_violation', 'Minimum Time Violation')], max_length=30, verbose_name='event type')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10, verbose_name='severity')),
                ('message', models.TextField(verbose_name='message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='courses.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='courses.assessmentsession')),
            ],
            options={
                'verbose_name': 'assessment audit log',
                'verbose_name_plural': 'assessment audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['user', 'quiz', 'is_active'], name='courses_ass_user_id_ef2477_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['session_token'], name='courses_ass_session_c078f4_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentauditlog',
            index=models.Index(fields=['user', 'event_type'], name='courses_ass_user_id_5c000d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentauditlog',
            index=models.Index(fields=['quiz', 'created_at'], name='courses_ass_quiz_id_03a374_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentauditlog',
            index=models.Index(fields=['severity', 'created_at'], name='courses_ass_severit_947f44_idx'),
        ),
    ]
