# Generated by Django 5.2.10 on 2026-01-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("failed_login", "Failed Login"),
                            ("register", "Register"),
                            ("password_change", "Password Change"),
                            ("profile_update", "Profile Update"),
                            ("lab_access", "Lab Access"),
                            ("command_execute", "Command Execute"),
                            ("admin_action", "Admin Action"),
                            ("api_request", "API Request"),
                        ],
                        max_length=50,
                        verbose_name="action",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="user agent"),
                ),
                (
                    "request_path",
                    models.CharField(max_length=500, verbose_name="request path"),
                ),
                (
                    "request_method",
                    models.CharField(max_length=10, verbose_name="request method"),
                ),
                (
                    "response_status",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="response status"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="extra data"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        unique=True, verbose_name="IP address"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("brute_force", "Brute Force Attack"),
                            ("suspicious", "Suspicious Activity"),
                            ("abuse", "Platform Abuse"),
                            ("manual", "Manually Blocked"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="reason",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "blocked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="blocked at"),
                ),
                (
                    "blocked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for permanent block",
                        null=True,
                        verbose_name="blocked until",
                    ),
                ),
            ],
            options={
                "verbose_name": "blocked IP",
                "verbose_name_plural": "blocked IPs",
            },
        ),
        migrations.CreateModel(
            name="RateLimitViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("endpoint", models.CharField(max_length=200, verbose_name="endpoint")),
                (
                    "violation_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="violation count"
                    ),
                ),
                (
                    "first_violation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="first violation"
                    ),
                ),
                (
                    "last_violation",
                    models.DateTimeField(auto_now=True, verbose_name="last violation"),
                ),
            ],
            options={
                "verbose_name": "rate limit violation",
                "verbose_name_plural": "rate limit violations",
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolved at"
                    ),
                ),
            ],
            options={
                "verbose_name": "security alert",
                "verbose_name_plural": "security alerts",
                "ordering": ["-severity", "-created_at"],
            },
        ),
    ]
