# Generated by Django 5.2.10 on 2026-01-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=1000, verbose_name="command")),
                ("output", models.TextField(blank=True, verbose_name="output")),
                (
                    "was_blocked",
                    models.BooleanField(default=False, verbose_name="was blocked"),
                ),
                (
                    "blocked_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="blocked reason"
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="executed at"),
                ),
            ],
            options={
                "verbose_name": "command log",
                "verbose_name_plural": "command logs",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulatedEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "filesystem",
                    models.JSONField(
                        default=dict,
                        help_text="JSON structure representing the simulated filesystem",
                        verbose_name="filesystem",
                    ),
                ),
                (
                    "network_config",
                    models.JSONField(
                        default=dict,
                        help_text="Simulated network hosts, open ports, services",
                        verbose_name="network config",
                    ),
                ),
                (
                    "simulated_user",
                    models.CharField(
                        default="student", max_length=50, verbose_name="simulated user"
                    ),
                ),
                (
                    "simulated_hostname",
                    models.CharField(
                        default="academy-lab",
                        max_length=100,
                        verbose_name="simulated hostname",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "simulated environment",
                "verbose_name_plural": "simulated environments",
            },
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "instructions",
                    models.TextField(
                        help_text="Step-by-step instructions for the student",
                        verbose_name="instructions",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="difficulty",
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(default=25, verbose_name="XP reward"),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="time limit (minutes)"
                    ),
                ),
                (
                    "allowed_commands",
                    models.JSONField(
                        default=list,
                        help_text="Commands allowed in this lab (empty = use global whitelist)",
                        verbose_name="allowed commands",
                    ),
                ),
                (
                    "objectives",
                    models.JSONField(
                        default=list,
                        help_text="List of objectives the student must complete",
                        verbose_name="objectives",
                    ),
                ),
                (
                    "hints",
                    models.JSONField(
                        default=list,
                        help_text="Hints that can be revealed progressively",
                        verbose_name="hints",
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        default=list,
                        help_text="Secret flags for CTF-style challenges",
                        verbose_name="flags",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labs",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab",
                "verbose_name_plural": "labs",
            },
        ),
        migrations.CreateModel(
            name="LabAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "completed_objectives",
                    models.JSONField(
                        default=list,
                        help_text="Indices of completed objectives",
                        verbose_name="completed objectives",
                    ),
                ),
                (
                    "hints_used",
                    models.PositiveIntegerField(default=0, verbose_name="hints used"),
                ),
                (
                    "commands_executed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="commands executed"
                    ),
                ),
                (
                    "xp_awarded",
                    models.BooleanField(default=False, verbose_name="XP awarded"),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="labs.lab",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab attempt",
                "verbose_name_plural": "lab attempts",
            },
        ),
    ]
