# Generated by Django 5.2.10 on 2026-01-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="solution_guide",
            field=models.TextField(
                blank=True,
                help_text="Step-by-step teaching content shown when user needs help",
                verbose_name="solution guide",
            ),
        ),
        migrations.AddField(
            model_name="lab",
            name="xp_penalty_for_solution",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Percentage of XP to deduct if solution is viewed (0-100)",
                verbose_name="XP penalty for viewing solution",
            ),
        ),
        migrations.AddField(
            model_name="labattempt",
            name="hints_revealed",
            field=models.JSONField(
                default=list,
                help_text="Indices of hints that have been revealed",
                verbose_name="hints revealed",
            ),
        ),
        migrations.AddField(
            model_name="labattempt",
            name="solution_viewed",
            field=models.BooleanField(
                default=False,
                help_text="User viewed the step-by-step solution",
                verbose_name="solution viewed",
            ),
        ),
    ]
